print('                  -----')
print('                 /    _`)')
print('                /    /')
print('      _.----.__/    /')
print('     /              /')
print('  __/    (  |    (  |')
print(' /__.---`|__|----|__|')